### ISSUE TITLE
Fix text going under the navbar on narrow screens

### ISSUE THREAD

**Issue by Madman10K** [Madman10K/MadLadSquadSite1.0#3]
On narrow screens if there is a lot of text it goes under the navbar

**Comment by ToluAkin** [comment]
Hi, Can I work on this?

**Comment by Madman10K** [comment]
Okay I will assign you to this issue and when you are ready you can submit a pull request

**Comment by ToluAkin** [comment]
@Madman10K I can not seem to replicate the issue but on the other pages, on small screens, the side navigation is not triggered like it is on the homepage. Can I work on fixing that for the the rest of the pages?

**Comment by Madman10K** [comment]
It seems like one of the pull requests I accepted has fixed the original issue and I resolved the navbar problem after the first pull request for the navbar rework. I will be marking this issue as closed thanks for checking it out!
